//@ts-nocheck
// scripts/seed-programs.ts
import { getPayload } from 'payload'
import configPromise from '@/payload.config'

async function seedPrograms() {
  try {
    const payload = await getPayload({ config: configPromise })

    const samplePrograms = [
      // DAY 1 — Thursday, 11 June 2026
      {
        title: 'Arrivals, Registration & Exhibition Viewing',
        description: 'Morning arrival, badge collection, and exhibition exploration',
        day: 'day-1',
        startTime: '08:00',
        endTime: '08:55',
        duration: '55m',
        type: 'registration',
        venue: 'main-lobby',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-blue-50 border-blue-200',
        order: 1,
      },
      {
        title: 'Opening Prayer',
        description: 'Opening prayer by Pastor Eunice Nyamuda',
        day: 'day-1',
        startTime: '08:55',
        endTime: '09:00',
        duration: '5m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-amber-50 border-amber-200',
        order: 2,
      },
      {
        title: 'Opening Remarks & Welcome Address',
        description: 'Welcome address by Mr Edward Nyamuda — Evolve ICT Summit',
        day: 'day-1',
        startTime: '09:00',
        endTime: '09:10',
        duration: '10m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-amber-50 border-amber-200',
        order: 3,
      },
      {
        title: 'Keynote: Building a Resilient Digital Zimbabwe',
        description: 'Infrastructure, Connectivity & the Road to Digital Sovereignty by Mr Simon Nyamuda, Managing Director, Compulink',
        day: 'day-1',
        startTime: '09:10',
        endTime: '09:40',
        duration: '30m',
        type: 'keynote',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-blue-50 border-blue-200',
        order: 4,
      },
      {
        title: 'Women in Cybersecurity',
        description: 'Spotlight on women in cybersecurity by Cordelia Allway, Security Engineer, Check Point',
        day: 'day-1',
        startTime: '09:40',
        endTime: '09:55',
        duration: '15m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 5,
      },
      {
        title: 'National Anthem',
        description: 'The National Anthem of Zimbabwe',
        day: 'day-1',
        startTime: '09:55',
        endTime: '10:00',
        duration: '5m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-amber-50 border-amber-200',
        order: 6,
      },
      {
        title: 'Introduction of the Guest of Honour',
        description: 'Formal introduction by Ministry of ICT, Postal & Courier Services Representative',
        day: 'day-1',
        startTime: '10:00',
        endTime: '10:05',
        duration: '5m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-amber-50 border-amber-200',
        order: 7,
      },
      {
        title: 'Guest of Honour Address',
        description: 'Address by Hon. Minister Tatenda Mavetera, Minister of ICT, Postal & Courier Services, Government of Zimbabwe',
        day: 'day-1',
        startTime: '10:05',
        endTime: '10:35',
        duration: '30m',
        type: 'keynote',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-blue-50 border-blue-200',
        order: 8,
      },
      {
        title: 'Tea Break, Exhibits & Networking',
        description: 'Refreshments and networking',
        day: 'day-1',
        startTime: '10:35',
        endTime: '11:30',
        duration: '55m',
        type: 'break',
        venue: 'exhibition-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-cyan-50 border-cyan-200',
        order: 9,
      },
      {
        title: 'Fintech, Financial Inclusion & the Digital Wallet Revolution in Africa',
        description: 'Presentation by Mr Bongani Zamchiya, Board Chairperson, Mukuru Zimbabwe',
        day: 'day-1',
        startTime: '11:30',
        endTime: '12:00',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'fintech',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 10,
      },
      {
        title: 'Artificial Intelligence in Telecommunications',
        description: 'How NetOne is Powering the Next Generation of Connectivity by Eng. Raphael Mushanawani, Group CEO, NetOne Cellular',
        day: 'day-1',
        startTime: '12:00',
        endTime: '12:30',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'ai',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 11,
      },
      {
        title: 'Panel 1: "Securing Africa\'s Digital Future: Trust, Tools & Transformation"',
        description: 'Moderated by Dr. Whisper Rukanda. Panelists: Simon Nyamuda, Eng. Raphael Mushanawani, Bongai Zamchiya, Cordelia Allway',
        day: 'day-1',
        startTime: '12:30',
        endTime: '13:00',
        duration: '30m',
        type: 'panel',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-purple-50 border-purple-200',
        order: 12,
      },
      {
        title: 'Lunch Break',
        description: 'Lunch and networking',
        day: 'day-1',
        startTime: '13:00',
        endTime: '14:00',
        duration: '1h',
        type: 'lunch',
        venue: 'dining-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-yellow-50 border-yellow-200',
        order: 13,
      },
      {
        title: 'AI-Powered Cybersecurity',
        description: 'Leveraging Artificial Intelligence to Detect, Respond & Recover by Riaz Hamiid Alqadri, Cybersecurity, Technology & Business Leader',
        day: 'day-1',
        startTime: '14:00',
        endTime: '14:30',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'security',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 14,
      },
      {
        title: 'CIRT in Action — Zimbabwe\'s National Cyber Incident Response Framework',
        description: 'Presentation by Zivo Keith Chamba, CIRT & Enforcement Manager, POTRAZ',
        day: 'day-1',
        startTime: '14:30',
        endTime: '15:00',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'security',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 15,
      },
      {
        title: 'Cybersecurity in the Age of AI',
        description: 'Protecting Enterprises and Critical Infrastructure by Mutsa Mabhande, CISO & Business Resilience Specialist',
        day: 'day-1',
        startTime: '15:00',
        endTime: '15:30',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'security',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 16,
      },
      {
        title: 'Panel 2: "The Human Firewall"',
        description: 'Cybersecurity Culture, Awareness & the Fight Against Social Engineering. Moderated by Nunudzai Mvera. Panelists: Riaz Hamiid Alqadri, Zivo Keith Chamba, Mutsa Mabhande, Tawanda Tongogara',
        day: 'day-1',
        startTime: '15:30',
        endTime: '16:00',
        duration: '30m',
        type: 'panel',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'security',
        featured: true,
        color: 'bg-purple-50 border-purple-200',
        order: 17,
      },
      {
        title: 'Day 1 Closing Announcements',
        description: 'Closing announcements for Day 1',
        day: 'day-1',
        startTime: '16:00',
        endTime: '16:05',
        duration: '5m',
        type: 'closing',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-rose-50 border-rose-200',
        order: 18,
      },
      {
        title: 'Exhibition & Business Matching',
        description: 'Extended exhibition and structured business matching',
        day: 'day-1',
        startTime: '16:05',
        endTime: '17:30',
        duration: '1h 25m',
        type: 'networking',
        venue: 'exhibition-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-green-50 border-green-200',
        order: 19,
      },
      // DAY 2 — Friday, 12 June 2026
      {
        title: 'Arrivals, Registration & Exhibition Viewing',
        description: 'Day 2 morning arrival and registration',
        day: 'day-2',
        startTime: '08:00',
        endTime: '08:55',
        duration: '55m',
        type: 'registration',
        venue: 'main-lobby',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-blue-50 border-blue-200',
        order: 1,
      },
      {
        title: 'Opening Prayer',
        description: 'Opening prayer for Day 2',
        day: 'day-2',
        startTime: '08:55',
        endTime: '09:00',
        duration: '5m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-amber-50 border-amber-200',
        order: 2,
      },
      {
        title: 'Welcome & Day 2 Remarks',
        description: 'Welcome address and Day 2 overview',
        day: 'day-2',
        startTime: '09:00',
        endTime: '09:10',
        duration: '10m',
        type: 'opening',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-amber-50 border-amber-200',
        order: 3,
      },
      {
        title: 'Keynote: Digital Transformation at Scale',
        description: 'How AI and Data are Redefining Telecoms & Business in Africa by Maria Chinomwe, AI Technology Services Executive, Econet Wireless Zimbabwe',
        day: 'day-2',
        startTime: '09:10',
        endTime: '09:40',
        duration: '30m',
        type: 'keynote',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-blue-50 border-blue-200',
        order: 4,
      },
      {
        title: 'Designing Zimbabwe\'s Digital Future',
        description: 'A Blueprint for National Digital Transformation by Dr Panashe Chiurunge, Chief AI Strategist',
        day: 'day-2',
        startTime: '09:40',
        endTime: '10:10',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 5,
      },
      {
        title: 'Panel 3: "Africa\'s Digital Economy — Fintech, AI & the Entrepreneurship Frontier"',
        description: 'Moderated by Kevin Ngalonde. Panelists: Maria Chinomwe, Dr Panashe Chiurunge, Dr Munyaradzi Gwatidzo, Neil Padmore',
        day: 'day-2',
        startTime: '10:10',
        endTime: '10:40',
        duration: '30m',
        type: 'panel',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'fintech',
        featured: true,
        color: 'bg-purple-50 border-purple-200',
        order: 6,
      },
      {
        title: 'Tea Break, Exhibits & Networking',
        description: 'Morning refreshments and networking',
        day: 'day-2',
        startTime: '10:40',
        endTime: '11:40',
        duration: '1h',
        type: 'break',
        venue: 'exhibition-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-cyan-50 border-cyan-200',
        order: 7,
      },
      {
        title: 'Smart Devices & Digital Transformation in Africa',
        description: 'Presentation by Duncan Asia, Samsung Senior Facilitator, Samsung Electronics',
        day: 'day-2',
        startTime: '11:40',
        endTime: '12:10',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 8,
      },
      {
        title: 'Panel 4: "From Local to Global — Scaling African Innovation"',
        description: 'Moderated by Rufaro Siwela. Panelists: Duncan Asia (Samsung), Daisy Mapingire – Matyatya (First Mutual Holdings), Mellany Msengezi',
        day: 'day-2',
        startTime: '12:10',
        endTime: '12:40',
        duration: '30m',
        type: 'panel',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'entrepreneurship',
        featured: true,
        color: 'bg-purple-50 border-purple-200',
        order: 9,
      },
      {
        title: 'Lunch Break',
        description: 'Lunch and networking',
        day: 'day-2',
        startTime: '13:00',
        endTime: '14:00',
        duration: '1h',
        type: 'lunch',
        venue: 'dining-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-yellow-50 border-yellow-200',
        order: 10,
      },
      {
        title: 'Panel 5: "From Summit to Action"',
        description: 'Building Africa\'s Regulatory Blueprint for a Thriving Digital Economy. Moderated by Allen Saruchera. Panelists: Dr Whisper Rukanda, Mr Freddy Ndhlovu, Taurai Thagalani, Garai Wekwete, Zivo Keith Chamba',
        day: 'day-2',
        startTime: '14:00',
        endTime: '15:00',
        duration: '1h',
        type: 'panel',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-purple-50 border-purple-200',
        order: 11,
      },
      {
        title: 'Summit Scribe Report',
        description: 'Key Insights, Resolutions & Actions Arising from the Evolve ICT Summit 2026',
        day: 'day-2',
        startTime: '15:00',
        endTime: '15:30',
        duration: '30m',
        type: 'talk',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: false,
        color: 'bg-indigo-50 border-indigo-200',
        order: 12,
      },
      {
        title: 'Closing Remarks & Vote of Thanks',
        description: 'Closing remarks and vote of thanks',
        day: 'day-2',
        startTime: '15:30',
        endTime: '15:45',
        duration: '15m',
        type: 'closing',
        venue: 'main-hall',
        capacity: 'All attendees',
        track: 'main',
        featured: true,
        color: 'bg-rose-50 border-rose-200',
        order: 13,
      },
      {
        title: 'Exhibition & Closing Networking',
        description: 'Final exhibition viewing and closing networking',
        day: 'day-2',
        startTime: '15:45',
        endTime: '17:30',
        duration: '1h 45m',
        type: 'networking',
        venue: 'exhibition-hall',
        capacity: 'All attendees',
        featured: false,
        color: 'bg-green-50 border-green-200',
        order: 14,
      },
    ]

    // Clear existing data
    const existingPrograms = await payload.find({
      collection: 'programs',
      limit: 1000,
    })

    for (const program of existingPrograms.docs) {
      await payload.delete({
        collection: 'programs',
        id: program.id,
      })
    }

    // Create new programs
    for (const program of samplePrograms) {
      await payload.create({
        collection: 'programs',
        data: program,
      })
      console.log(`Created program: ${program.title}`)
    }

    console.log('Programs seeded successfully!')
    process.exit(0)
  } catch (error) {
    console.error('Error seeding programs:', error)
    process.exit(1)
  }
}

// Run the script
if (require.main === module) {
  seedPrograms()
}
