/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    registrations: Registration;
    tickets: Ticket;
    payments: Payment;
    speakers: Speaker;
    programs: Program;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: string;
  email: string;
  type: 'attendee' | 'sponsor' | 'exhibitor';
  status?: ('pending' | 'approved' | 'rejected' | 'paid' | 'cancelled') | null;
  orderId?: string | null;
  amount: number;
  paymentMethod?: ('card' | 'mobile' | 'bank' | 'pending') | null;
  attendeeDetails?: {
    fullName: string;
    phone: string;
    organization: string;
    position: string;
    country: string;
    ticketType: 'early-bird-1' | 'early-bird-2' | 'regular';
    dietaryRestrictions?: string | null;
  };
  sponsorDetails?: {
    companyName: string;
    contactPerson: string;
    phone: string;
    website?: string | null;
    sponsorshipTier: 'platinum' | 'gold' | 'silver' | 'bronze';
    companyDescription: string;
    numberOfTeamMembers: number;
    teamMembers: string;
    interestedInBooth?: boolean | null;
  };
  exhibitorDetails?: {
    companyName: string;
    contactPerson: string;
    phone: string;
    website?: string | null;
    industry: string;
    productsServices: string;
    boothSize: 'small' | 'medium' | 'large';
    boothNumber?: string | null;
    numberOfTeamMembers: number;
    teamMembers: string;
    specialRequirements?: string | null;
  };
  qrCode?: (string | null) | Media;
  paymentProof?: (string | null) | Media;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  name: string;
  description?: string | null;
  type: 'attendee' | 'sponsor' | 'exhibitor';
  subType?:
    | (
        | 'early-bird-1'
        | 'early-bird-2'
        | 'regular'
        | 'platinum'
        | 'gold'
        | 'silver'
        | 'bronze'
        | 'small'
        | 'medium'
        | 'large'
      )
    | null;
  price: number;
  quantity: number;
  available?: number | null;
  earlyBirdEnd?: string | null;
  benefits?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  registration: string | Registration;
  transactionId?: string | null;
  amount: number;
  currency?: ('USD' | 'ZWL') | null;
  paymentMethod: 'card' | 'mobile' | 'bank' | 'cash';
  status?: ('pending' | 'processing' | 'completed' | 'failed' | 'refunded') | null;
  paymentProof?: (string | null) | Media;
  mobileMoneyDetails?: {
    provider?: ('ecocash' | 'onemoney' | 'telecash') | null;
    phoneNumber?: string | null;
    transactionCode?: string | null;
  };
  bankTransferDetails?: {
    bankName?: string | null;
    accountNumber?: string | null;
    reference?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: string;
  name: string;
  photo?: (string | null) | Media;
  organization: string;
  designation: string;
  bio: string;
  expertise?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  twitter?: string | null;
  website?: string | null;
  email?: string | null;
  featured?: boolean | null;
  sessions?: (string | Program)[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: string;
  title: string;
  description: string;
  day: 'day-1' | 'day-2';
  /**
   * Specific date of the session
   */
  date?: string | null;
  startTime: string;
  endTime: string;
  /**
   * e.g., 1h, 30m, 1.5h
   */
  duration: string;
  type:
    | 'keynote'
    | 'panel'
    | 'workshop'
    | 'talk'
    | 'networking'
    | 'registration'
    | 'opening'
    | 'closing'
    | 'lunch'
    | 'break';
  track?: ('main' | 'ai' | 'security' | 'cloud' | 'fintech' | 'entrepreneurship' | 'social') | null;
  speaker?: (string | null) | Speaker;
  speakerName?: string | null;
  speakerTitle?: string | null;
  venue:
    | 'main-auditorium'
    | 'room-a'
    | 'room-b'
    | 'room-c'
    | 'exhibition-hall'
    | 'dining-hall'
    | 'networking-lounge'
    | 'grand-ballroom'
    | 'main-lobby';
  /**
   * e.g., All attendees, 500 attendees, Invitation only
   */
  capacity?: string | null;
  featured?: boolean | null;
  color?:
    | (
        | 'bg-blue-50 border-blue-200'
        | 'bg-purple-50 border-purple-200'
        | 'bg-amber-50 border-amber-200'
        | 'bg-green-50 border-green-200'
        | 'bg-red-50 border-red-200'
        | 'bg-indigo-50 border-indigo-200'
        | 'bg-yellow-50 border-yellow-200'
        | 'bg-gray-50 border-gray-200'
        | 'bg-cyan-50 border-cyan-200'
      )
    | null;
  /**
   * Link for session registration (optional)
   */
  registrationLink?: string | null;
  materials?:
    | {
        title?: string | null;
        file?: (string | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'registrations';
        value: string | Registration;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'speakers';
        value: string | Speaker;
      } | null)
    | ({
        relationTo: 'programs';
        value: string | Program;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  email?: T;
  type?: T;
  status?: T;
  orderId?: T;
  amount?: T;
  paymentMethod?: T;
  attendeeDetails?:
    | T
    | {
        fullName?: T;
        phone?: T;
        organization?: T;
        position?: T;
        country?: T;
        ticketType?: T;
        dietaryRestrictions?: T;
      };
  sponsorDetails?:
    | T
    | {
        companyName?: T;
        contactPerson?: T;
        phone?: T;
        website?: T;
        sponsorshipTier?: T;
        companyDescription?: T;
        numberOfTeamMembers?: T;
        teamMembers?: T;
        interestedInBooth?: T;
      };
  exhibitorDetails?:
    | T
    | {
        companyName?: T;
        contactPerson?: T;
        phone?: T;
        website?: T;
        industry?: T;
        productsServices?: T;
        boothSize?: T;
        boothNumber?: T;
        numberOfTeamMembers?: T;
        teamMembers?: T;
        specialRequirements?: T;
      };
  qrCode?: T;
  paymentProof?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  subType?: T;
  price?: T;
  quantity?: T;
  available?: T;
  earlyBirdEnd?: T;
  benefits?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  registration?: T;
  transactionId?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  status?: T;
  paymentProof?: T;
  mobileMoneyDetails?:
    | T
    | {
        provider?: T;
        phoneNumber?: T;
        transactionCode?: T;
      };
  bankTransferDetails?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        reference?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  organization?: T;
  designation?: T;
  bio?: T;
  expertise?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  linkedin?: T;
  twitter?: T;
  website?: T;
  email?: T;
  featured?: T;
  sessions?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  day?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  type?: T;
  track?: T;
  speaker?: T;
  speakerName?: T;
  speakerTitle?: T;
  venue?: T;
  capacity?: T;
  featured?: T;
  color?: T;
  registrationLink?: T;
  materials?:
    | T
    | {
        title?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  notes?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}